# ===============================================================
# FILE: application.yml (của config-server, phiên bản cập nhật)
# ===============================================================
server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///C:/Users/DAT/OneDrive - ut.edu.vn/Documents/Desktop/EV-Charging-Station-Management-System---Project/backend/services/config-repo"

        # ====================================================
        # [COMMAND]: THÊM KHỐI NÀY VÀO
        # Buộc tất cả các client phải ghi đè các thuộc tính này,
        # giải quyết vấn đề "con gà và quả trứng".
        overrides:
          # Yêu cầu tất cả client đăng ký bằng IP thay vì hostname
          eureka.instance.prefer-ip-address: true
        # ====================================================

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/