# ===============================================================
# FILE: application.yml (của user-service, phiên bản đã sửa lỗi)
# ===============================================================

server:
  port: 9000

spring:
  application:
    # Tên của service, sẽ được đăng ký trên Eureka là USER-SERVICE
    name: user-service

  # Cấu hình để import cấu hình từ Config Server
  config:
    import: "optional:configserver:http://localhost:8888"

  # Cấu hình kết nối cơ sở dữ liệu
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: huynhdat123@