# ===============================================================
# FILE: api-gateway.yml
# LOCATION: config-repo/api-gateway.yml
# ===============================================================

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # USER SERVICE
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        # STATION SERVICE - Stations
        - id: station-route
          uri: lb://STATION-SERVICE
          predicates:
            - Path=/api/stations/**

        # STATION SERVICE - Chargers
        - id: charger-route
          uri: lb://STATION-SERVICE
          predicates:
            - Path=/api/chargers/**

        # CHARGING SERVICE
        - id: charging-service-route
          uri: lb://CHARGING-SERVICE
          predicates:
            - Path=/api/sessions/**

        # PAYMENT SERVICE - Payments
        - id: payment-route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**

        # PAYMENT SERVICE - Wallets
        - id: wallet-route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/wallets/**

      # Global CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      # Load Balancer
      loadbalancer:
        cache:
          enabled: false

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.web: DEBUG

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,routes,refresh
  endpoint:
    gateway:
      enabled: true