# ===============================================================
# FILE: api-gateway.yml (Phiên bản đã sửa lỗi và thêm Filter)
# LOCATION: config-repo/api-gateway.yml
# ===============================================================

server:
  port: 8080 # Cổng Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    gateway:
      # [COMMAND]: TẮT discovery locator để chỉ dùng route tường minh
      discovery:
        locator:
          enabled: false

      # [COMMAND]: Các quy tắc định tuyến tường minh
      routes:
        # --- Route cho Auth Service (KHÔNG cần filter) ---
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/** # Cho phép login, validate

        # --- Các route cần bảo vệ ---
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER

        - id: station-service-routes
          uri: lb://STATION-SERVICE
          predicates:
            - Path=/api/stations/**, /api/chargers/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER

        - id: charging-service-route
          uri: lb://CHARGING-SERVICE
          predicates:
            - Path=/api/sessions/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER

        - id: payment-service-routes
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**, /api/wallets/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER

        - id: notification-service-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER

      # Global CORS (Nhớ thu hẹp origins cho production)
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # Chỉ dùng "*" khi dev
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      # Load Balancer
      loadbalancer:
        cache:
          enabled: false

# Logging (Giữ DEBUG khi dev để dễ dò lỗi)
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: INFO
    org.springframework.web: INFO

# Actuator (Giữ nguyên)
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,routes,refresh
  endpoint:
    gateway:
      enabled: true