# ===============================================================
# FILE: api-gateway.yml (Phiên bản cuối cùng, đã sửa lỗi)
# ===============================================================

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # [COMMAND]: Yêu cầu Gateway cập nhật danh bạ từ Eureka mỗi 5 giây
    registry-fetch-interval-seconds: 5

  # Cấu hình này đã được chuyển vào file application.yml chung
  # instance:
  #   prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: station-service-route
          uri: lb://STATION-SERVICE
          predicates:
            - Path=/api/stations/**, /api/chargers/**
        - id: charging-service-route
          uri: lb://CHARGING-SERVICE
          predicates:
            - Path=/api/sessions/**

    # [COMMAND]: Cấu hình cho Load Balancer của Gateway
    loadbalancer:
      # Tắt cache để Gateway luôn lấy dữ liệu mới nhất từ Eureka (chỉ dùng khi dev)
      cache:
        enabled: false