server:
  port: 8088 # Cổng mới cho loyalty-service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loyalty_service_db?useSSL=false
    username: root # Thay bằng username của bạn
    password: huynhdat123@ # Thay bằng mật khẩu của bạn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Cấu hình kết nối RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    non-secure-port: ${server.port}

# Cấu hình tên exchange/queue cho RabbitMQ (sẽ dùng ở bước sau)
app:
  rabbitmq:
    exchange: payment_events # Giả sử lắng nghe sự kiện từ payment
    queue: loyalty_queue