server:
  port: 8085 # Chạy notification-service trên cổng mới

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Cấu hình mail server (ví dụ dùng Gmail - cần bật "Less secure app access" hoặc App Password)
  mail:
    host: smtp.gmail.com
    port: 587
    username: huynhphongdat2005@gmail.com
    password: dapp xywu xmag ahdh
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  rabbitmq:
    host: localhost # Địa chỉ RabbitMQ broker (đang chạy trên Docker)
    port: 5672     # Cổng AMQP mặc định
    username: guest  # Username mặc định
    password: guest  # Password mặc định
app:
  rabbitmq:
    exchange: charging_events # Tên exchange sẽ lắng nghe
    queue: notification_queue # Tên queue sẽ lắng nghe
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/