server:
  port: 8085 # Chạy notification-service trên cổng mới

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Cấu hình mail server (ví dụ dùng Gmail - cần bật "Less secure app access" hoặc App Password)
  mail:
    host: smtp.gmail.com
    port: 587
    username: huynhphongdat2005@gmail.com
    password: dapp xywu xmag ahdh
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/