server:
  port: 8085 # Chạy notification-service trên cổng mới

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_service_db?useSSL=false
    username: root # Thay bằng username của bạn
    password: your_password # Thay bằng mật khẩu của bạn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Cấu hình mail server (ví dụ dùng Gmail - cần bật "Less secure app access" hoặc App Password)
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com # Email của bạn
    password: your-app-password # Mật khẩu ứng dụng hoặc mật khẩu email
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/